### ISSUE TITLE
If invalid name/ID is entered and valid name/ID is entered after, program enters infinite loop.

### ISSUE THREAD

**Issue by ryanrouleau** [tuliotorezan/Eldar_Torezan_CSCI2270_FinalProject#2]
For example, if you go to general information, then "Search Pokemon by Name/Number" and enter an invalid name, the program asks for a correct input.  The issue is that when you enter a correct ID (e.g. 059), the program does not accept it and will keep printing that it is an invalid name/ID each time it is entered.  This appears to be happing in all places where the user searches by name/ID.

**Comment by ryanrouleau** [comment]
This appears to happen whenever the user inputs something invalid and then something valid.  For example, it is also occurring when searching by height.  If you enter something invalid, then H, it enters the same kind of infinite loop.

**Comment by tomeldar** [comment]
1. When searching for a Pokemon by ID/Name and you enter an invalid name, it asks you for a valid name and not an ID, thus, it is reasonable for the program not to continue if you enter an ID.
2. In regards to the second issue mentioned, the issue has been fixed.

Thank you for your feedback! It is very appreciated!
