### ISSUE TITLE
When user selects "Random Curiosity" and enters a non-integer, the program locks up.

### ISSUE THREAD

**Issue by ryanrouleau** [tuliotorezan/Eldar_Torezan_CSCI2270_FinalProject#3]
If you select the third menu option "Random Curiosity" and enter anything other than an integer, the program goes into an infinite loop which appears to clear the screen than prints "Please enter a..." over and over.  The program can not be exited even with ctrl-c and has to be force killed from activity monitor when this occurs.

**Comment by tomeldar** [comment]
Thank you for your feedback! This option has been fixed.
