### ISSUE TITLE
Facts could use More Instructions

### ISSUE THREAD

**Issue by Tarah-Peltz** [tuliotorezan/Eldar_Torezan_CSCI2270_FinalProject#8]
When a user navigates to a fact page, they are taken to an awesome page with information about the Pokémon with the highest or lowest stats based on type, size, etc. However, there are no instructions on how to navigate backwards. This can be achieved by hitting enter. Instructions to do so could be useful to the user.

**Comment by Tarah-Peltz** [comment]
I fixed this in my latest commit of PokemonEntris2.cpp

**Comment by tomeldar** [comment]
The issue has been resolved. Thank you for your feedback!
